version: '3.8'

services:
    frontend:
        build: "./ds2023_30643_turcu_cezar_frontend"
        ports:
            - "3000:3000"
        networks:
            ems-network:
                ipv4_address: 192.168.0.6

    users_service:
        build:
            context: "./ds2023_30643_turcu_cezar_users"
        ports:
            - "8080:8080"
        depends_on:
            - "users_db"
        networks:
            ems-network:
                ipv4_address: 192.168.0.5
        environment:
            - SPRING_PROFILES_ACTIVE=dev

    devices_service:
        build: "./ds2023_30643_turcu_cezar_devices"
        ports:
            - "8081:8081"
        depends_on:
            - "devices_db"
        networks:
            ems-network:
                ipv4_address: 192.168.0.4
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_RABBITMQ_HOST=rabbitmq_desktop

    users_db:
        container_name: 'users-db-container'
        image: postgres:14.1-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'users'
        networks:
            ems-network:

    devices_db:
        container_name: 'devices-db-container'
        image: postgres:14.1-alpine
        ports:
            - '5431:5432'
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'devices'
        networks:
            ems-network:

    rabbitmq_desktop:
        image: rabbitmq:3-management
        container_name: 'rabbitmq_desktop'
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            ems-network:
                ipv4_address: 192.168.0.8

    mc_db:
        container_name: 'mc-db-container'
        image: postgres:14.1-alpine
        ports:
            - '5433:5432'
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'mc'
        networks:
            ems-network:
                ipv4_address: 192.168.0.15


    mc_service:
        build: "./ds_2023_30643_turcu_cezar_monitoring_communication"
        ports:
            - "8082:8082"
        depends_on:
            - rabbitmq_desktop
            - mc_db
        networks:
            ems-network:
                ipv4_address: 192.168.0.16
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_RABBITMQ_HOST=rabbitmq_desktop
            - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true


    chat_service:
        build: "./ds2023_30643_turcu_cezar_chat"
        ports:
            - "8083:8083"
        networks:
            ems-network:
                ipv4_address: 192.168.0.17

networks:
    ems-network:
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"