server:
  port: 8080

spring:
  application:
    name: ems-users

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

client:
  devices: http://localhost:8081
